-- Ensure booking.status allows COMPLETED (version 2 so it applies after baseline)
ALTER TABLE BOOKING DROP CONSTRAINT IF EXISTS CONSTRAINT_2;
ALTER TABLE BOOKING ADD CONSTRAINT CONSTRAINT_2 CHECK (
  STATUS IN ('PENDING','ACCEPTED','REJECTED','PAID','CONFIRMED','COMPLETED')
);
